/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author cesarleonel
 */
public class vAbout extends javax.swing.JFrame {

    /**
     * Creates new form vAbout
     */
    public vAbout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbout = new javax.swing.JPanel();
        lbnombreE = new javax.swing.JLabel();
        lbCarneE = new javax.swing.JLabel();
        lbCorreoE = new javax.swing.JLabel();
        lbTelefonoE = new javax.swing.JLabel();
        lbnombre = new javax.swing.JLabel();
        lbCarne = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbnombreE.setText("nombre:");

        lbCarneE.setText("carne:");

        lbCorreoE.setText("correo:");

        lbTelefonoE.setText("telefono:");

        lbnombre.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        lbnombre.setText("Cesar Leonel Chamale Sican");

        lbCarne.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        lbCarne.setText("201700634");

        lbCorreo.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        lbCorreo.setText("cesarchamalesican@gmail.com");

        lbTelefono.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        lbTelefono.setText("31482997");

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTelefonoE)
                    .addComponent(lbCorreoE)
                    .addComponent(lbCarneE)
                    .addComponent(lbnombreE))
                .addGap(18, 18, 18)
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbnombre)
                    .addComponent(lbCarne)
                    .addComponent(lbCorreo)
                    .addComponent(lbTelefono))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnombreE)
                    .addComponent(lbnombre))
                .addGap(36, 36, 36)
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarneE)
                    .addComponent(lbCarne))
                .addGap(35, 35, 35)
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorreoE)
                    .addComponent(lbCorreo))
                .addGap(28, 28, 28)
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefonoE)
                    .addComponent(lbTelefono))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vAbout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCarne;
    private javax.swing.JLabel lbCarneE;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbCorreoE;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTelefonoE;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbnombreE;
    private javax.swing.JPanel panelAbout;
    // End of variables declaration//GEN-END:variables
}
